# Generated by Django 4.2.6 on 2023-11-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
